version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    image: registry.digitalocean.com/auto-canon/be-node-app:latest
    container_name: node-app
    ports:
      - "3001:3001"
    restart: on-failure
    volumes:
      - /home/amogh/uploads:/app/uploads
    environment:
      PORT : 3001
      MONGO_IP : mongo-db
      MONGO_USER : mongo
      MONGO_PWD : mongo
      MONGO_PORT : 27017
      ACCESS_TOKEN_SECRET : 41f0d950a8446b745b919bec8d3fe68e51a5e3c1ad2a7fe5c1dc2a0af12d09f08de7b5877f5d90c880a03dbdf479a719bb7ca58ec58d62cd392fa48c5088c23e
      ADMIN_SIGNUP_TOKEN_SECRET: 37c2d99757b540ed55748fcf49d9924746bd
      SENDGRID_API_KEY : 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
     NEW_SIGNIN_URL : https://bv-reg.com/NewSignin
      RESET_PASSWORD : https://bv-reg.com/ResetPassword
    depends_on:
      - mongo-db
    command: npm run start
  
  mongo-db:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME : mongo
      MONGO_INITDB_ROOT_PASSWORD : mongo
    volumes:
      - /home/amogh/mongo-data:/data/db